# Generated by Django 4.0.3 on 2022-06-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0009_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='empregado',
            field=models.CharField(max_length=3),
        ),
    ]
