# Generated by Django 4.0.3 on 2022-06-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0011_alter_aluno_empregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='empregado2',
            field=models.CharField(default='', max_length=3),
        ),
    ]
