# Generated by Django 4.0.3 on 2022-06-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0012_aluno_empregado2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='empregado2',
        ),
    ]
